# Generated by Django 3.1.7 on 2023-10-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completes',
            new_name='completed',
        ),
    ]
